const $=id=>document.getElementById(id),wrap=$("wrap"),canvas=$("canvas"),layer=$("layer"),svg=$("svg"),empty=$("empty");
let nodes=[],edges=[],selected=new Set(),zoom=1,hist=[],future=[],counter=1,drag=null,resize=null,pan=null,connect=null;
const D={start:["Start / End",150,70],process:["Process",150,70],decision:["Decision",110,110],data:["Data",150,70],document:["Document",150,75],database:["Database",150,75],circle:["Circle",80,80],hexagon:["Hexagon",145,75],parallelogram:["Data",150,70]};
function snap(v){return Math.round(v/10)*10} function pt(e){let r=wrap.getBoundingClientRect();return{x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom}}
function saveState(){hist.push(JSON.stringify({nodes,edges,zoom}));if(hist.length>80)hist.shift();future=[]}
function restore(s){let d=JSON.parse(s);nodes=d.nodes||[];edges=d.edges||[];zoom=d.zoom||1;selected.clear();render();setZoom(zoom)}
function undo(){if(!hist.length)return;future.push(JSON.stringify({nodes,edges,zoom}));restore(hist.pop());status("Undo")}
function redo(){if(!future.length)return;hist.push(JSON.stringify({nodes,edges,zoom}));restore(future.pop());status("Redo")}
function status(t){$("status").textContent=t}
function get(id){return nodes.find(n=>n.id===id)}
function add(type,x,y){saveState();let d=D[type];nodes.push({id:"n"+counter++,type,x:snap(x-d[1]/2),y:snap(y-d[2]/2),w:d[1],h:d[2],text:d[0],fill:"#ffffff",border:"#334155",font:16,line:2});selected=new Set([nodes.at(-1).id]);render();status("Shape added")}
function side(n,side){return side==="t"?{x:n.x+n.w/2,y:n.y}:side==="r"?{x:n.x+n.w,y:n.y+n.h/2}:side==="b"?{x:n.x+n.w/2,y:n.y+n.h}:{x:n.x,y:n.y+n.h/2}}
function near(n,p){let a=["t","r","b","l"].map(s=>[s,side(n,s)]);a.sort((A,B)=>Math.hypot(A[1].x-p.x,A[1].y-p.y)-Math.hypot(B[1].x-p.x,B[1].y-p.y));return a[0][0]}
function connectTo(a,b){if(a===b||edges.some(e=>e.a===a&&e.b===b))return;saveState();edges.push({a,b});render();status("Connected")}
function render(){layer.innerHTML="";svg.querySelectorAll(".edge").forEach(x=>x.remove());
nodes.forEach(n=>{let e=document.createElement("div");e.className=`node ${n.type} ${selected.has(n.id)?"selected":""}`;e.dataset.id=n.id;e.style.cssText=`left:${n.x}px;top:${n.y}px;width:${n.w}px;height:${n.h}px;--fill:${n.fill};background:${n.fill};border-color:${n.border};border-width:${n.line}px;font-size:${n.font}px`;
let t=document.createElement("div");t.className="txt";t.textContent=n.text;e.append(t);
["t","r","b","l"].forEach(s=>{let p=document.createElement("span");p.className=`port ${s}`;p.onpointerdown=x=>startConnect(x,n.id,s);e.append(p)});
["h-t","h-r","h-b","h-l"].forEach((s,i)=>{let h=document.createElement("span");h.className=`handle ${s}`;h.onpointerdown=x=>startResize(x,n.id,i);e.append(h)});
e.onpointerdown=x=>startDrag(x,n.id);e.ondblclick=x=>edit(n);layer.append(e)});
edges.forEach(c=>{let a=get(c.a),b=get(c.b);if(!a||!b)return;let p1=side(a,near(a,{x:b.x+b.w/2,y:b.y+b.h/2})),p2=side(b,near(b,{x:a.x+a.w/2,y:a.y+a.h/2})),l=document.createElementNS("http://www.w3.org/2000/svg","line");l.classList.add("edge");l.setAttribute("x1",p1.x);l.setAttribute("y1",p1.y);l.setAttribute("x2",p2.x);l.setAttribute("y2",p2.y);svg.append(l)});empty.style.display=nodes.length?"none":"block";props()}
function startDrag(e,id){if(e.target.classList.contains("port")||e.target.classList.contains("handle"))return;if(e.button!==0)return;if(!e.shiftKey)selected=new Set([id]);else selected.has(id)?selected.delete(id):selected.add(id);render();saveState();let p=pt(e),base=get(id);drag={x:p.x,y:p.y,ids:[...selected],baseX:base.x,baseY:base.y};document.addEventListener("pointermove",moveDrag);document.addEventListener("pointerup",endDrag,{once:true})}
function moveDrag(e){if(!drag)return;let p=pt(e),dx=snap(p.x-drag.x),dy=snap(p.y-drag.y);let b=get(drag.ids[0]);drag.ids.forEach(id=>{let n=get(id);n.x+=dx;n.y+=dy});drag.x=p.x;drag.y=p.y;render();status("Moving")}
function endDrag(){document.removeEventListener("pointermove",moveDrag);drag=null;status("Moved")}
function startResize(e,id,corner){e.stopPropagation();if(!selected.has(id))selected=new Set([id]);saveState();resize={id,corner,start:pt(e),n:{...get(id)}};document.addEventListener("pointermove",moveResize);document.addEventListener("pointerup",endResize,{once:true})}
function moveResize(e){let r=resize,p=pt(e),n=get(r.id),dx=p.x-r.start.x,dy=p.y-r.start.y,o=r.n;if(r.corner===1){n.w=Math.max(40,snap(o.w+dx))}else if(r.corner===2){n.h=Math.max(30,snap(o.h+dy))}else if(r.corner===3){n.x=snap(o.x+dx);n.w=Math.max(40,snap(o.w-dx))}else{n.y=snap(o.y+dy);n.h=Math.max(30,snap(o.h-dy))}render()}
function endResize(){document.removeEventListener("pointermove",moveResize);resize=null;status("Resized")}
function startConnect(e,id,s){e.stopPropagation();let n=get(id);connect={id,start:side(n,s)};let mv=x=>{drawTemp(x)},up=x=>{document.removeEventListener("pointermove",mv);document.removeEventListener("pointerup",up);let target=x.target.closest(".node");if(target)connectTo(id,target.dataset.id);else render();connect=null};document.addEventListener("pointermove",mv);document.addEventListener("pointerup",up)}
function drawTemp(e){if(!connect)return;svg.querySelectorAll(".temp").forEach(x=>x.remove());let p=pt(e),l=document.createElementNS("http://www.w3.org/2000/svg","line");l.classList.add("temp");l.setAttribute("x1",connect.start.x);l.setAttribute("y1",connect.start.y);l.setAttribute("x2",p.x);l.setAttribute("y2",p.y);svg.append(l)}
function edit(n){let v=prompt("Edit text:",n.text);if(v!==null){saveState();n.text=v;render();status("Text updated")}}
function props(){let n=selected.size===1?get([...selected][0]):null;$("props").classList.toggle("disabled",!n);if(!n){$("pText").value="";return}$("pText").value=n.text;$("pW").value=n.w;$("pH").value=n.h;$("pX").value=n.x;$("pY").value=n.y;$("pFill").value=n.fill;$("pBorder").value=n.border;$("pFont").value=n.font;$("pLine").value=n.line}
function change(k,v){let n=selected.size===1?get([...selected][0]):null;if(!n)return;saveState();n[k]=v;render();status("Updated")}
$("pText").onchange=e=>change("text",e.target.value);$("pW").onchange=e=>change("w",Math.max(40,+e.target.value));$("pH").onchange=e=>change("h",Math.max(30,+e.target.value));$("pX").onchange=e=>change("x",+e.target.value);$("pY").onchange=e=>change("y",+e.target.value);$("pFill").oninput=e=>{let n=selected.size===1?get([...selected][0]):null;if(n){n.fill=e.target.value;render()}};$("pBorder").oninput=e=>{let n=selected.size===1?get([...selected][0]):null;if(n){n.border=e.target.value;render()}};$("pFont").onchange=e=>change("font",+e.target.value);$("pLine").onchange=e=>change("line",+e.target.value);
$("del").onclick=()=>{if(!selected.size)return;saveState();let ids=[...selected];nodes=nodes.filter(n=>!ids.includes(n.id));edges=edges.filter(e=>!ids.includes(e.a)&&!ids.includes(e.b));selected.clear();render();status("Deleted")};
$("dup").onclick=()=>{if(!selected.size)return;saveState();let ns=[...selected].map(id=>{let n={...get(id),id:"n"+counter++,x:get(id).x+20,y:get(id).y+20};return n});nodes.push(...ns);selected=new Set(ns.map(n=>n.id));render();status("Duplicated")};
$("bring").onclick=()=>{if(!selected.size)return;saveState();let ids=[...selected],a=nodes.filter(n=>ids.includes(n.id)),b=nodes.filter(n=>!ids.includes(n.id));nodes=[...b,...a];render();status("Brought to front")};
document.querySelectorAll(".item").forEach(i=>i.ondragstart=e=>e.dataTransfer.setData("type",i.dataset.type));wrap.ondragover=e=>e.preventDefault();wrap.ondrop=e=>{e.preventDefault();let type=e.dataTransfer.getData("type");if(type){let p=pt(e);add(type,p.x,p.y)}};
wrap.onpointerdown=e=>{if(e.target!==wrap)return;if(e.button===1||e.shiftKey){pan={x:e.clientX,y:e.clientY,sx:wrap.scrollLeft,sy:wrap.scrollTop};document.addEventListener("pointermove",movePan);document.addEventListener("pointerup",endPan,{once:true})}else{selected.clear();render()}};
function movePan(e){wrap.scrollLeft=pan.sx-(e.clientX-pan.x);wrap.scrollTop=pan.sy-(e.clientY-pan.y)}function endPan(){document.removeEventListener("pointermove",movePan);pan=null}
function setZoom(z){zoom=Math.min(2.5,Math.max(.35,z));canvas.style.transform=`scale(${zoom})`;$("zoom").textContent=Math.round(zoom*100)+"%";render()}
$("zoomIn").onclick=()=>setZoom(zoom+.1);$("zoomOut").onclick=()=>setZoom(zoom-.1);$("fit").onclick=()=>{if(!nodes.length)return setZoom(1);let minX=Math.min(...nodes.map(n=>n.x)),maxX=Math.max(...nodes.map(n=>n.x+n.w)),minY=Math.min(...nodes.map(n=>n.y)),maxY=Math.max(...nodes.map(n=>n.y+n.h)),r=wrap.getBoundingClientRect();setZoom(Math.min(1.4,Math.max(.45,Math.min((r.width-80)/(maxX-minX+100),(r.height-80)/(maxY-minY+100)))));wrap.scrollLeft=Math.max(0,minX*zoom-40);wrap.scrollTop=Math.max(0,minY*zoom-40)};
$("undo").onclick=undo;$("redo").onclick=redo;$("save").onclick=()=>{localStorage.setItem("flowchartV2",JSON.stringify({nodes,edges,zoom}));status("Saved locally")};
$("export").onclick=()=>{let blob=new Blob([JSON.stringify({nodes,edges},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="flowchart.json";a.click();status("JSON exported")};
$("search").oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll(".item").forEach(i=>i.style.display=i.textContent.toLowerCase().includes(q)?"flex":"none")};
document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"){e.preventDefault();$("dup").click()}if(e.key==="Delete"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName))$("del").click();if(e.key==="Escape"){selected.clear();render()}};
let autosave=setInterval(()=>localStorage.setItem("flowchartV2",JSON.stringify({nodes,edges,zoom})),5000);
render();
